version: "3.8"

services:
  db:
    image: mysql:9.3.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: spring_with_rest
    ports:
      - "3308:3306"
    networks:
      - gui-network

  spring-with-rest:
    build: .
    image: guibsantos/spring-with-rest
    restart: always
    working_dir: /spring_with_rest
    ports:
      - "80:80"
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spring_with_rest?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - gui-network
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - gui-network
volumes:
  portainer_data:

networks:
  gui-network:
    driver: bridge
