name: Continuous Integration and Delivery with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build Application .jar
        run: mvn clean package

      - name: Docker Compose Build
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag guibsantos/spring-with-rest:latest ${{ secrets.DOCKER_USERNAME }}/spring-with-rest:latest
          docker tag guibsantos/spring-with-rest:latest ${{ secrets.DOCKER_USERNAME }}/spring-with-rest:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-with-rest:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-with-rest:${{ github.run_id }}
